#!/bin/bash

# Clone the repo or pull from remote if
# already exists
function hgpullclone () {
    remote_repo=$1
    local_co=$2
    if [ -d "$local_co" ]; then
        hg pull "$remote_repo" -R "$local_co" > /dev/null
    else
        hg clone "$remote_repo" "$local_co" > /dev/null
    fi
}

# Clone the repo or pull from remote if
# already exists
function gitpullclone () {
    remote_repo=$1
    local_co=$2
    if [ -d "$local_co" ]; then
        pushd "$local_co" > /dev/null
        git pull "$remote_repo" master &> /dev/null
        popd > /dev/null
    else
        git clone "$remote_repo" "$local_co" &> /dev/null
    fi
}

if [ 1 != $# -a 2 != $# ]; then
    echo "usage: $0 bitbucket_username [github_username]";
    exit 1;
fi

bbusername=$1
if [ -z "$2" ]; then
    ghusername=$bbusername;
else
    ghusername=$2;
fi

if [ '-l' = "$bbusername" ]; then
    bbusername=$ghusername
fi

repourl="https://api.bitbucket.org/1.0/users/$bbusername/"

json=`curl --silent --show-error $repourl`
repos=`echo "$json"|python -c '
import sys;
import json; 
d=json.load(sys.stdin); 
for r in d["repositories"]:
    print "%s,%s" % (r["slug"],r["scm"])
'`

# Just list the bitbucket repos
if [ "-l" = "$1" ]; then
    for repo in $repos; do
        reponame=`echo $repo|cut -d ',' -f 1`
        scm=`echo $repo|cut -d ',' -f 2`
        echo "$reponame ($scm)"
    done
    exit 0;
fi

codir="/tmp"
for repo in $repos; do
    reponame=`echo $repo|cut -d ',' -f 1`
    scm=`echo $repo|cut -d ',' -f 2`
    echo -n "Mirroring $reponame via $scm... "
    repourl="https://bitbucket.org/$bbusername/$reponame"
    repodir="$codir/$reponame"
    if [ 'hg' = "$scm" ]; then
        hgpullclone "$repourl" "$repodir"
        hg push "git+ssh://git@github.com/$ghusername/$reponame" -R "$repodir" > /dev/null
        echo "done";
    elif [ 'git' = "$scm" ]; then
        gitpullclone "$repourl" "$repodir"
        pushd "$repodir" > /dev/null
        git push "ssh://git@github.com/$ghusername/$reponame.git" &> /tmp/bb2gh-git-output
        if [ $? != 0 ]; then
            echo ""; # throw a new line due to '-n' used above
            cat /tmp/bb2gh-git-output
            rm /tmp/bb2gh-git-output
            exit 1;
        fi
        rm /tmp/bb2gh-git-output
        popd > /dev/null
        echo "done";
    else
        echo "skipped, can't handle scm $scm";
    fi
done

